# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 08:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170929_0837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='friend',
            new_name='friend_profile',
        ),
        migrations.RenameField(
            model_name='friend',
            old_name='user',
            new_name='user_profile',
        ),
    ]
