# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-18 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20171018_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='city',
        ),
        migrations.AlterField(
            model_name='race',
            name='race_location',
            field=models.CharField(default='Bristol', max_length=255),
        ),
    ]
